name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.2

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: linwu05
        password: ${{ secrets.FENGWENHAO_05 }}
        
        
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags: |
          linwu05/boot-cicd-demo:${{ github.run_number }}
          linwu05/boot-cicd-demo
